version: '3'

services:
  php-7.3.14:
    build:
        context: .
        dockerfile: ./7.3.14/Dockerfile
    container_name: php-7.3.14 
    volumes:
       - ./html:/var/www/html
    ports:
       - 4000:80

  php-5.6.4:
    build:
        context: .
        dockerfile: ./5.6.4/Dockerfile
    container_name: php-5.6.4
    volumes:
       - ./html:/var/www/html
    ports:
       - 4001:80
