version: '3'

services:
  php-7.3.14:
    build:
        context: .
        dockerfile: ./7.3.14/Dockerfile
    container_name: php-7.3.14 
    volumes:
       - ./html:/var/www/html
    ports:
       - 4001:80

  php-5.6.4:
    build:
        context: .
        dockerfile: ./5.6.4/Dockerfile
    container_name: php-5.6.4
    volumes:
       - ./html:/var/www/html
    ports:
       - 4002:80

  php-5.1.6:
    build:
        context: .
        dockerfile: ./5.1.6/Dockerfile
    container_name: php-5.1.6
    volumes:
       - ./html:/var/www/html
    ports:
       - 4003:80
